// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qursphxkahqmagmgyoaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cnNwaHhrYWhxbWFnbWd5b2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDg4NjcsImV4cCI6MjA2ODM4NDg2N30.Nx25JEXnhIcbk6Dg5wjj9bNULD-SEvzepBUyhHrHW34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});